#!/usr/bin/expect -f

set timeout 1000
set host cdweb@114.141.173.17
set pswd xxxx

spawn scp -r /Users/admin/WorkSpace/FoodAiWeb/FAweb/ $host:/home/cdweb

# spawn scp -r ./ss.sh $host:/home/cdweb
expect "*assword:"
send "$pswd\r"
expect eof

spawn ssh -p 22 cdweb@114.141.173.17

expect  "*password:" { send "$pswd\r" }
expect  "$*" { send "scp -r /home/cdweb/FAweb root@192.168.42.2:/var/www/html/aidev\r" }

interact

